# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Docker Setup Buildx'
description: 'Set up Docker Buildx'
author: 'docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  version:
    description: 'Buildx version. (eg. v0.3.0)'
    required: false
  driver:
    description: 'Sets the builder driver to be used'
    default: 'docker-container'
    required: false
  driver-opts:
    description: 'List of additional driver-specific options. (eg. image=moby/buildkit:master)'
    required: false
  buildkitd-flags:
    description: 'Flags for buildkitd daemon'
    default: '--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host'
    required: false
  install:
    description: 'Sets up docker build command as an alias to docker buildx'
    default: 'false'
    required: false
  use:
    description: 'Switch to this builder instance'
    default: 'true'
    required: false
  endpoint:
    description: 'Optional address for docker socket or context from `docker context ls`'
    required: false
  config:
    description: 'BuildKit config file'
    required: false
  config-inline:
    description: 'Inline BuildKit config'
    required: false

outputs:
  name:
    description: 'Builder name'
  driver:
    description: 'Builder driver'
  endpoint:
    description: 'Builder node endpoint'
  status:
    description: 'Builder node status'
  flags:
    description: 'Builder node flags (if applicable)'
  platforms:
    description: 'Builder node platforms available (comma separated)'

runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
